server.port=5555

db.url=jdbc:mysql://localhost:3306/foreign_languages_school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Minsk&allowPublicKeyRetrieval=true&useSSL=false
db.username=root
db.password=1111

db.pool.size=10

server.thread.pool.size=20

auth.max.attempts=3

auth.lockout.minutes=15
